# Generated by Django 4.0 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditlog", "0015_alter_logentry_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="actor",
            field=models.CharField(
            max_length=255, verbose_name=_("actor")),
        ),
    ]
